<?php declare(strict_types=1);
namespace Fode\CommunicationLedger\Http;
use Fode\CommunicationLedger\Config\Config; use Fode\CommunicationLedger\Ledger\Repository; use Fode\CommunicationLedger\Auth\HmacAuthenticator; use Fode\CommunicationLedger\Commands\CommandHandler;
final class App {
    private const CONTRACT_VERSION = '1.0';
    public function __construct(private Config $config,private Repository $repo) {}
    public function run(): never { $path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH); $method=$_SERVER['REQUEST_METHOD']??'GET'; if ($method==='GET' && in_array($path,['/health','/version','/schema'],true)) $this->publicStatus($path); $body=file_get_contents('php://input') ?: ''; try { (new HmacAuthenticator($this->config,$this->repo))->verify($method,$path,$body,$this->headers()); if($method==='POST'&&$path==='/commands') { $request=json_decode($body,true,512,JSON_THROW_ON_ERROR); if (($request['contractVersion']??null) !== self::CONTRACT_VERSION) Response::json(400,['contractVersion'=>self::CONTRACT_VERSION,'error'=>'UNSUPPORTED_CONTRACT_VERSION']); Response::json(200,['contractVersion'=>self::CONTRACT_VERSION]+(new CommandHandler($this->repo))->handle($request)); } Response::json(404,['contractVersion'=>self::CONTRACT_VERSION,'error'=>'NOT_FOUND']); } catch(\InvalidArgumentException $e) { Response::json(400,['contractVersion'=>self::CONTRACT_VERSION,'error'=>'MALFORMED_REQUEST']); } catch(\RuntimeException $e) { Response::json(str_starts_with($e->getMessage(),'Conflicting command replay') ? 409 : 401,['contractVersion'=>self::CONTRACT_VERSION,'error'=>str_starts_with($e->getMessage(),'Conflicting command replay') ? 'IDEMPOTENCY_CONFLICT' : 'REQUEST_REJECTED']); } catch(\Throwable $e) { Response::json(500,['contractVersion'=>self::CONTRACT_VERSION,'error'=>'INTERNAL_ERROR']); } }
    private function publicStatus(string $path): never { try { $base=['available'=>true,'environment'=>$this->config->get('environment'),'serviceVersion'=>$this->config->get('service_version'),'contractVersion'=>self::CONTRACT_VERSION,'database'=>'connected','utcTimestamp'=>gmdate('c')]; if($path==='/version') Response::json(200,['serviceVersion'=>$base['serviceVersion'],'contractVersion'=>self::CONTRACT_VERSION]); if($path==='/schema') Response::json(200,['schemaVersion'=>$this->repo->schemaVersion(),'contractVersion'=>self::CONTRACT_VERSION]); Response::json(200,$base+['schemaVersion'=>$this->repo->schemaVersion()]); } catch(\Throwable) { Response::json(503,['contractVersion'=>self::CONTRACT_VERSION,'available'=>false,'database'=>'unavailable','utcTimestamp'=>gmdate('c')]); } }
    private function headers(): array { $out=[]; foreach($_SERVER as $k=>$v) if(str_starts_with($k,'HTTP_')) $out[strtolower(str_replace('_','-',substr($k,5)))]=(string)$v; return $out; }
}
